### PR TITLE
Fix workflow issues

### PR DESCRIPTION
**Pull request by HalosGhost**
Includes:

* explicitly setup go dependencies
* update make target names

Signed-off-by: Sam Stuewe <stuewe@mit.edu>

### CODE REVIEW

**Comment by HalosGhost** [comment]
Sorry this took me a while to get handled, but I think it should all be working now. I'll fix anything that comes up with the CI!

**Comment by HalosGhost** [comment]
Mmm, I don't think I can fix that one; the log looks like it's to do with authentication Sonar (which I'm unfamiliar with anyway).

Let me know how I can be helpful in resolving it though!

**Comment by DavyLandman** [comment]
No need to apologize, it's our own free time right?

GH protects secrets from externel PRs, so that's the reason the QA one is failing. So this is no problem to worry about.

**Review by DavyLandman — APPROVED** [review]

**Comment by HalosGhost** [comment]
Very much so! Thank you for understanding and I hope I didn't cause too much of a disruption! ☺

**Pull request merged**
